/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import javax.servlet.http.HttpServletResponse;

import org.apache.http.HttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.Test;

import controllers.Controller;

public class MainRequestRouterTest {
    private static Logger lgr;
    private CloseableHttpClient httpClient = HttpClients.createDefault();
    
    // some necessary initializations to make logging and web server
    // work with junit
    static {
        MainRequestRouter.initLogger();
        lgr = LogManager.getLogger(MainRequestRouterTest.class);
        MainRequestRouter.lgr = LogManager.getLogger(MainRequestRouter.class);
        lgr.info("Starting...");
        (new MainRequestRouter()).run();        
    }
    
    @Test public void testThatIndexHTTPGetReturnsCorrectSizePayload() 
            throws UnsupportedOperationException, IOException 
    {
        HttpGet get = new HttpGet("http://localhost/");
        int code = -1;
        HttpResponse response = null;
        try {
            response = httpClient.execute(get);
            code = response.getStatusLine().getStatusCode();
        } catch (Exception e) {}
        assertEquals(code, HttpServletResponse.SC_OK);
        BufferedReader br = 
                new BufferedReader(
                        new InputStreamReader(
                                response.getEntity().getContent()));
        int httpResponsePayloadLength = 0;
        String line;
        while ((line = br.readLine()) != null) {
            // remove all line breaks, since OS dependent line break syntax
            // might cause differences in results
            line = line.replace("\n", "").replace("\r", "");
            httpResponsePayloadLength += line.length();
        }
        String indexFile = Controller.readTemplate("index.html");
        // remove all line breaks, since OS dependent line break syntax
        // might cause differences in results
        indexFile = indexFile.replace("\n", "").replace("\r", "");
        assertEquals(httpResponsePayloadLength, indexFile.length());
    }
}
