/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class ServerComponentTest {
    @Test public void testSomeLibraryMethod() {
        //ServerComponent classUnderTest = new ServerComponent();
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
